### ISSUE TITLE
Max, min value of the counter input

### ISSUE THREAD

**Issue by RiadMohamed** [WrathChaos/react-native-counter-input#4]

**Comment by kuraydev** [comment]
Hello @RiadMohamed,
I've corrected your issue title and description. Please do not open an issue just like that :) 

Actually you can set your max min value by handling yourself with using `onChange` method. Simply you can state the counter input's value and check that it is in the max and min value limits.

**Comment by RiadMohamed** [comment]
Thank you, I do manage this internally and there is no issues in that department. However, since I use it mostly to get head count on people, having negative values isn't really applicable per say. So I was wondering if there was any way I can make the visible counter within the view component to stop at 0.

PS: I know, and as I have mentioned I was aware it's more of an enquiry than an issue, sorry chief

**Comment by kuraydev** [comment]
@RiadMohamed You can set the state value to 0 if even user tried to make it below. Therefore, user cannot see any negative value. 

I hope I did not misunderstand what you mean.

**Comment by RiadMohamed** [comment]
Hello (sorry for the late reply), no you got me right that's what I am trying to do. I did go through the interface props and I can't see a way to change the counter value from the onDecreasePress method, I know I am probably missing something so any hints ?

**Comment by RiadMohamed** [comment]
Hello (sorry for the late reply), no you are right that's exactly what I am trying to do and I did manage to get it done. I did what you mentioned and it works like a charm. In details, I added the IF statement I needed in the CounterInput.js file and in the this.handleOnDecreasePress method inside the constructor. Thanks for you help, appreciate it.
