### ISSUE TITLE
Setting a minimum number on the counter input

### ISSUE THREAD

**Issue by iamrita** [WrathChaos/react-native-counter-input#5]
Would it be possible to make so it so that the user cannot go past 0 into the negatives for this tool. Is there a way to do that currently now, or would that it be a feature you would have to add to the tool. I really want to use it, but I don't want the user to be able to submit a negative number.

**Comment by Tiagopt3** [comment]
Hi, i currently have an open PR #6, which have these feature, u can set a min and max value.

**Comment by kuraydev** [comment]
Merged with #6 and [1.0.0](https://github.com/WrathChaos/react-native-counter-input/releases/tag/1.0.0) released version :)
